---
- hosts: hq
  tasks:
  - name: admin packages
    package:
      name: "{{item}}"
      state: present
    with_items:
      - tmux
      - xauth
      - xclip
      - htop
      - mosh
    become: yes
  - name: dotfiles
    copy:
      src: files/{{item}}
      dest: ~/.{{item}}
    with_items:
      - bash_aliases
      - tmux.conf
      - pythonrc.py
  - name: source dotfiles in bashrc
    lineinfile:
      dest: ~/.bashrc
      line: "{{item}}"
      state: present
      insertafter: EOF
      create: yes
    with_items:
      - ". ~/.bash_aliases"
      - "export PYTHONSTARTUP=~/.pythonrc.py"
