# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
ZSH_THEME="blinks"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git jump vagrant)

# User configuration

export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/pallav/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Adding for jump tab completion
function _completemarks {
  reply=($(ls $MARKPATH))
}

compctl -K _completemarks jump
compctl -K _completemarks unmark
# End jump completion

## Custom awesomeness (could be moved to a separate file)

export PATH="/usr/local/texlive/2014/bin/x86_64-darwin:/opt/phab/arcanist/bin:/usr/local/Cellar/gcc/4.9.2_1/bin:/usr/local/opt/coreutils/libexec/gnubin:$PATH"
export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
export VIRTUALENVWRAPPER_SCRIPT=/usr/local/bin/virtualenvwrapper.sh
source /usr/local/bin/virtualenvwrapper_lazy.sh
export GOPATH='/Users/pallav/gocode'

export EDITOR="vim"
# export EDITOR="subl -w"
export ANSIBLE_NOCOWS=1
function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.

# Change default functionality
unalias ls
alias ls="ls --color"
alias ssh="ssh -X"
# alias mosh="LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 mosh"
# May need to uncomment 'AcceptEnv LANG LC_*' from host's sshd_config
# TODO find a permanent way to deal with language problems
alias mosh="mosh -p 60000:61000"

alias ll="ls | lolcat"
alias lh="ls -laSh"
alias lash="ls -laSh"

alias gbm="git branch --merged master"
alias gdc="git diff --cached"
alias glp="git log --color -p"
alias gls="git log --stat --color --oneline --graph"
alias glg="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias hlog='git log --date-order --all --graph --format="%C(green)%h %Creset%C(yellow)%an%Creset %C(blue bold)%ar%Creset %C(red bold)%d%Creset %s"'
alias cdg="cd \$(git rev-parse --show-toplevel)"
alias gauthors="git log --format='%aN' | sort | uniq -c | sort -rn"
# Count commits in the range range merge-base HEAD master
alias grcountmaster="git rev-list --count master.."
alias grc="git rev-list --count"
# Unalias dangerous and annoying stuff
unalias gstp
unalias gp
unalias gk

alias j="jump"
alias fucking="sudo"
alias year="cal -y"
alias ssum="sha256sum"
alias vg="vagrant global-status"
alias vs="vagrant shell"
alias t="tmux attach"
alias seditrc="subl ~/.zshrc"
alias seditansiblehosts="subl /usr/local/etc/ansible/hosts"
alias seditsshconfig="subl ~/.ssh/config"
alias editrc="vim ~/.zshrc"
alias editansiblehosts="vim /usr/local/etc/ansible/hosts"
alias editsshconfig="vim ~/.ssh/config"

# Just for fun! (http://yjyao.com/2014/09/colorful-cowsay-in-your-terminal.html)
fortune | cowsay -f $(cowsay -l | tail -n +2 | tr ' ' '\n' | gshuf -n 1) | lolcat
